// <auto-generated />
using System;
using BDParamsRefonteDraft.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BDParamsRefonteDraft.Migrations
{
    [DbContext(typeof(BDParamsContext))]
    [Migration("20221224082017_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BDParamsRefonteDraft.Models.Entities.Capteur", b =>
                {
                    b.Property<Guid>("CapteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeleID")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CapteurId");

                    b.HasIndex("ModeleID");

                    b.ToTable("Capteurs");
                });

            modelBuilder.Entity("BDParamsRefonteDraft.Models.Entities.Modele", b =>
                {
                    b.Property<Guid>("ModeleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ModeleID");

                    b.ToTable("Modeles");
                });

            modelBuilder.Entity("BDParamsRefonteDraft.Models.Entities.Parametre", b =>
                {
                    b.Property<Guid>("ParametreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ModeleID")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Valeur")
                        .HasColumnType("double precision");

                    b.HasKey("ParametreId");

                    b.HasIndex("ModeleID");

                    b.ToTable("Parametres");
                });

            modelBuilder.Entity("BDParamsRefonteDraft.Models.Entities.Capteur", b =>
                {
                    b.HasOne("BDParamsRefonteDraft.Models.Entities.Modele", "Modele")
                        .WithMany()
                        .HasForeignKey("ModeleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modele");
                });

            modelBuilder.Entity("BDParamsRefonteDraft.Models.Entities.Parametre", b =>
                {
                    b.HasOne("BDParamsRefonteDraft.Models.Entities.Modele", null)
                        .WithMany("Parametres")
                        .HasForeignKey("ModeleID");
                });

            modelBuilder.Entity("BDParamsRefonteDraft.Models.Entities.Modele", b =>
                {
                    b.Navigation("Parametres");
                });
#pragma warning restore 612, 618
        }
    }
}
